config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  mount ApiRoot => ApiRoot::PREFIX
  mount GrapeSwaggerRails::Engine => '/apidoc'
  resources :courses
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/course.rb
# == Schema Information
#
# Table name: courses
#
#  id          :bigint           not null, primary key
#  category    :integer          default("programming")
#  currency    :integer          default("ntd")
#  description :text
#  duration    :integer
#  price       :float
#  status      :integer          default("online")
#  subject     :string
#  url         :text
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#
class Course < ApplicationRecord
  # Scope macros

  # Concerns macros

  # Constants

  # Attributes related macros
  enum category: { programming: 0, project_management: 1 }
  enum currency: { ntd: 0, usd: 1 }
  enum status: { offline: 0, online: 1 }

  # Association macros

  # Association through macros

  # Validation macros
  validates :category, :currency, :status, :subject, :url, presence: true
  validates :duration, presence: true, numericality: { greater_than_or_equal_to: 1, less_than_or_equal_to: 30 }
  validates :price, presence: true, numericality: { greater_than: 0 }
  validates :category, inclusion: { in: categories.keys }
  validates :currency, inclusion: { in: currencies.keys }
  validates :status, inclusion: { in: statuses.keys }
  validates :url, url: true

  # Callbacks

  # Other
end

app/models/order.rb
# == Schema Information
#
# Table name: orders
#
#  id         :bigint           not null, primary key
#  category   :integer          default("programming")
#  expired_at :datetime
#  snapshot   :jsonb            not null
#  subject    :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  user_id    :bigint
#
# Indexes
#
#  index_orders_on_category  (category)
#  index_orders_on_subject   (subject)
#  index_orders_on_user_id   (user_id)
#
# Foreign Keys
#
#  fk_rails_...  (user_id => users.id)
#
class Order < ApplicationRecord
  # Scope macros
  scope :available, -> { where('expired_at > ?', Time.now) }

  # Concerns macros

  # Constants

  # Attributes related macros
  enum category: Course.categories

  # Association macros
  belongs_to :user

  # Association through macros

  # Validation macros
  validates :category, :expired_at, :snapshot, :subject, presence: true
  validates :category, inclusion: { in: Course.categories.keys }

  # Callbacks
  before_create :set_expired_at

  # Other

  private

  def set_expired_at
    self.expired_at = Time.now + snapshot['duration'].days
  end
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id                     :bigint           not null, primary key
#  email                  :string           default(""), not null
#  encrypted_password     :string           default(""), not null
#  jti                    :string           not null
#  remember_created_at    :datetime
#  reset_password_sent_at :datetime
#  reset_password_token   :string
#  role                   :integer          default("general")
#  created_at             :datetime         not null
#  updated_at             :datetime         not null
#
# Indexes
#
#  index_users_on_email                 (email) UNIQUE
#  index_users_on_jti                   (jti) UNIQUE
#  index_users_on_reset_password_token  (reset_password_token) UNIQUE
#
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  # Scope macros

  # Concerns macros

  # Constants

  # Attributes related macros
  enum role: { general: 0, admin: 1 }

  # Association macros
  has_many :orders, dependent: :destroy

  # Association through macros

  # Validation macros

  # Callbacks
  before_create :generate_jti

  # Other

  private

  def generate_jti
    self.jti = SecureRandom.hex(16)
    loop do
      break unless User.exists?(jti: jti)

      self.jti ||= SecureRandom.hex(16)
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protected

  def authenticate_admin
    redirect_to '/', alert: 'Not authorized.' unless current_user.admin?
  end
end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
  before_action :authenticate_user!
  before_action :authenticate_admin
  before_action :set_course, only: %i[show edit update destroy]

  # GET /courses
  def index
    @courses = Course.all
  end

  # GET /courses/1
  def show; end

  # GET /courses/new
  def new
    @course = Course.new
  end

  # GET /courses/1/edit
  def edit; end

  # POST /courses
  def create
    @course = Course.new(course_params)

    respond_to do |format|
      if @course.save
        format.html { redirect_to @course, notice: 'Course was successfully created.' }
      else
        format.html { render :new, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /courses/1 or /courses/1.json
  def update
    respond_to do |format|
      if @course.update(course_params)
        format.html { redirect_to @course, notice: 'Course was successfully updated.' }
      else
        format.html { render :edit, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /courses/1 or /courses/1.json
  def destroy
    @course.destroy
    respond_to do |format|
      format.html { redirect_to courses_url, notice: 'Course was successfully destroyed.' }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_course
    @course = Course.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def course_params
    params
      .require(:course)
      .permit(:subject, :price, :currency, :category, :status, :url, :description, :duration)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/courses/_form.html.erb
<%= form_with(model: course, local: true) do |form| %>
  <% if course.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(course.errors.count, "error") %> prohibited this course from being saved:</h2>

      <ul>
      <% course.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :subject %>
    <%= form.text_field :subject %>
  </div>

  <div class="field">
    <%= form.label :price %>
    <%= form.number_field :price, value: form.object.price.to_f, step: :any %>
  </div>

  <div class="field">
    <%= form.label :currency %>
    <%= form.select :currency, options_for_select(Course.currencies.keys) %>
  </div>

  <div class="field">
    <%= form.label :category %>
    <%= form.select :category, options_for_select(Course.categories.keys) %>
  </div>

  <div class="field">
    <%= form.label :status %>
    <%= form.select :status, options_for_select(Course.statuses.keys) %>
  </div>

  <div class="field">
    <%= form.label :url %>
    <%= form.text_area :url %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description %>
  </div>

  <div class="field">
    <%= form.label :duration %>
    <%= form.number_field :duration, in: 1..30 %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/courses/edit.html.erb
<h1>Editing Course</h1>

<%= render 'form', course: @course %>

<%= link_to 'Show', @course %> |
<%= link_to 'Back', courses_path %>

app/views/courses/index.html.erb
<h1>Courses</h1>

<table>
  <thead>
    <tr>
      <th>Subject</th>
      <th>Price</th>
      <th>Currency</th>
      <th>Category</th>
      <th>Status</th>
      <th>Url</th>
      <th>Description</th>
      <th>Duration</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @courses.each do |course| %>
      <tr>
        <td><%= course.subject %></td>
        <td><%= course.price %></td>
        <td><%= course.currency %></td>
        <td><%= course.category %></td>
        <td><%= course.status %></td>
        <td><%= course.url %></td>
        <td><%= course.description %></td>
        <td><%= course.duration %></td>
        <td><%= link_to 'Show', course %></td>
        <td><%= link_to 'Edit', edit_course_path(course) %></td>
        <td><%= link_to 'Destroy', course, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Course', new_course_path %>

app/views/courses/new.html.erb
<h1>New Course</h1>

<%= render 'form', course: @course %>

<%= link_to 'Back', courses_path %>

app/views/courses/show.html.erb
<p>
  <strong>Subject:</strong>
  <%= @course.subject %>
</p>

<p>
  <strong>Price:</strong>
  <%= @course.price %>
</p>

<p>
  <strong>Currency:</strong>
  <%= @course.currency %>
</p>

<p>
  <strong>Category:</strong>
  <%= @course.category %>
</p>

<p>
  <strong>Status:</strong>
  <%= @course.status %>
</p>

<p>
  <strong>Url:</strong>
  <%= @course.url %>
</p>

<p>
  <strong>Description:</strong>
  <%= @course.description %>
</p>

<p>
  <strong>Duration:</strong>
  <%= @course.duration %>
</p>

<%= link_to 'Edit', edit_course_path(@course) %> |
<%= link_to 'Back', courses_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Mycourse</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <p class='notice'><%= notice %></p>
    <p class='alert'><%= alert %></p>

    <% if current_user %>
      <%= link_to('登出', destroy_user_session_path, :method => :delete) %>
      <%= link_to('修改密碼', edit_registration_path(:user)) %>
    <% else %>
      <%= link_to('註冊', new_registration_path(:user)) %> |
      <%= link_to('登入', new_session_path(:user)) %>
    <% end %>

    <%= yield %>
  </body>
</html>